cf_shop-master/config/routes.rb
Rails.application.routes.draw do

  resources :products do
    resources :comments
  end
  resources :users

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :orders, only: [:index, :show, :create, :destroy]
  post 'payments/create'

  get 'static_pages/about'

  get 'static_pages/contact'
  post 'static_pages/thank_you'

  get 'static_pages/index'

  root 'static_pages#landing_page'

end

cf_shop-master/app/views/layouts/_head.html.erb
<head>
  <title>CfShop</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>

cf_shop-master/app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">CF Bike Shop</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= "active" if params[:controller] == "products" %>"><%= link_to "Products", products_path %></li>
        <li><%= link_to "Orders", orders_path %></li>
      </ul>

      <!-- Search Form -->
		  <%= form_tag("/products", method: "get", class: "navbar-form navbar-left") do %>
		  	<div class="form-group">
				  <%= text_field_tag(:q, nil, class: "form-control", placeholder: "Search") %>
				</div>
				  <%= submit_tag("Search", class: "btn btn-default") %>
			<% end %>

		<!-- Devise actions -->
		<ul class="nav navbar-nav navbar-right">
			<% if user_signed_in? %>
			  <li>
			  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
			  </li>
			<% else %>
			  <li>
			  <%= link_to('Login', new_user_session_path)  %>
			  </li>
			<% end %>
		</ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

cf_shop-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/head' %>

<body>
	<div class="container">
		<%= render 'layouts/nav' %>

		<div class="flash-notices">
		  <p class="notice text-info"><%= notice %></p>
		  <p class="alert text-danger"><%= alert %></p>
		</div>

		<%= yield %>

	</div>
</body>

</html>